apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-pvc
spec:
  storageClassName: standard
  accessModes:
    - {{ .Values.redis.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.pvc.storage }}
