apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-rolebinding
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: flask-app-namespace
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io
