apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  DB_NAME: {{ .Values.configmap.data.DB_NAME }}
  DB_USER: {{ .Values.configmap.data.DB_USER }}
  DB_HOST: {{ .Values.configmap.data.DB_HOST }}
  DB_PORT: "{{ .Values.configmap.data.DB_PORT }}"
  REDIS_HOST: {{ .Values.configmap.data.REDIS_HOST }}
  REDIS_PORT: "{{ .Values.configmap.data.REDIS_PORT }}"
